stages:
  - setup
  - test

setup-python-36:
  stage: setup
  script:
    - python36 -m venv env
    - source env/bin/activate
    - pip install -U pip setuptools
    - pip install -e .[cython]

test-build-python-36:
  stage: test:build
  script:
    - python36 -m venv env
    - source env/bin/activate
    - pip install -U pip setuptools pytest
    - pip install -e .[cython]
    - cd test
    - python setup.py build
    - pytest F2x_test
