stages:
  - build
  - test

setup-python-36:
  stage: build
  script:
    - python36 -m venv env
    - source env/bin/activate
    - pip install -U pip setuptools
    - pip install -e .[cython]
  tags:
    - bacardi

test-build-python-36:
  stage: test
  script:
    - python36 -m venv env
    - source env/bin/activate
    - pip install -U pip setuptools pytest
    - pip install -e .[cython]
    - cd test
    - python setup.py build
    - pytest F2x_test
  tags:
    - bacardi
