MODULE SOURCE

CONTAINS

    SUBROUTINE BASIC_ARGS_IN(ININT, INREAL, INLOGICAL)
        INTEGER, INTENT(IN) :: ININT
        REAL(8), INTENT(IN) :: INREAL
        LOGICAL, INTENT(IN) :: INLOGICAL

        WRITE (*,*) ININT, INREAL, INLOGICAL
    END SUBROUTINE

    SUBROUTINE BASIC_ARGS_OUT(OUTINT, OUTREAL, OUTLOGICAL)
        INTEGER, INTENT(OUT) :: OUTINT
        REAL(8), INTENT(OUT) :: OUTREAL
        LOGICAL, INTENT(OUT) :: OUTLOGICAL

        OUTINT = 1
        OUTREAL = 2.3
        OUTLOGICAL = .TRUE.
    END SUBROUTINE

    SUBROUTINE BASIC_ARGS_INOUT(INOUTINT, INOUTREAL, INOUTLOGICAL)
        INTEGER, INTENT(INOUT) :: INOUTINT
        REAL(8), INTENT(INOUT) :: INOUTREAL
        LOGICAL, INTENT(INOUT) :: INOUTLOGICAL

        INOUTINT = INOUTINT * 2
        INOUTREAL = INOUTREAL / 2
        INOUTLOGICAL = .NOT. INOUTLOGICAL
    END SUBROUTINE

    SUBROUTINE BASIC_ARGS_ARRAY(INARRAY, OUTARRAY, INOUTARRAY)
        INTEGER, INTENT(IN) :: INARRAY(:)
        INTEGER, INTENT(OUT) :: OUTARRAY(:)
        INTEGER, INTENT(INOUT) :: INOUTARRAY(:)

        WRITE (*,*) INARRAY(:), INOUTARRAY(:)
        OUTARRAY = [4, 5, 6]
        INOUTARRAY(1) = INOUTARRAY(2)
    END SUBROUTINE

    SUBROUTINE STRING_ARGS(INSTR, OUTSTR, INOUTSTR)
        CHARACTER(32), INTENT(IN) :: INSTR
        CHARACTER(32), INTENT(OUT) :: OUTSTR
        CHARACTER(32), INTENT(INOUT) :: INOUTSTR

        OUTSTR = INSTR
    END SUBROUTINE

END
