{#-##################################################################################################################-#}
{#- F2x 'ctypes' main template.                                                                                      -#}
{#-                                                                                                                  -#}
{#- This template generates Python wrappers for FORTRAN `TYPE`s, `SUBROUTINE`s and `FUNCTION`s based on ctypes and   -#}
{#- NumPy for handling arrays.                                                                                       -#}
{#-                                                                                                                  -#}
{#- Copyright 2018 German Aerospace Center (DLR)                                                                     -#}
{#-                                                                                                                  -#}
{#- Licensed under the Apache License, Version 2.0 (the "License");                                                  -#}
{#- you may not use this file except in compliance with the License.                                                 -#}
{#- You may obtain a copy of the License at                                                                          -#}
{#-                                                                                                                  -#}
{#-     http://www.apache.org/licenses/LICENSE-2.0                                                                   -#}
{#-                                                                                                                  -#}
{#- Unless required by applicable law or agreed to in writing, software                                              -#}
{#- distributed under the License is distributed on an "AS IS" BASIS,                                                -#}
{#- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.                                         -#}
{#- See the License for the specific language governing permissions and                                              -#}
{#- limitations under the License.                                                                                   -#}
{#-##################################################################################################################-#}


{#- Import helper libraries. -#}
{%- import "types.py.tl" as types with context -%}
{%- import "methods.py.tl" as methods with context -%}
{%- import "marshal/bind.py.tl" as bind with context -%}


# This module was generated by the F2x 'ctypes' template. Please do not modify directly.
import ctypes

{{ bind.py_import() }}

{{ bind.lib_import() }}

{%- if module.methods %}
#===================================================================================================================
# Exported subroutines and functions
    {%- for method in module.methods %}
{{ methods.export(method) }}
    {% endfor %}
{%- endif %}
