! This file was generated by F2x. Please do not edit directly.
MODULE {{ src.module_name }}_WRAP
	USE, INTRINSIC :: ISO_C_BINDING
	USE WRAP_UTIL
{%- for use in src.uses %}
	USE {{ use.name }}
{%- endfor %}
	USE {{ src.module_name }}
	
	IMPLICIT NONE

CONTAINS
{%- for type_def in src.type_defs %}
	
	!------------------------------------------------------------
	! Interface for {{ type_def.name }} from {{ src.module_name }}.
	!
	FUNCTION {{ type_def.name }}_NEW() BIND('C', NAME="{{ type_def.name }}_new")
		TYPE(C_PTR) :: {{ type_def.name }}_NEW
		TYPE({{ type_def.name }}), POINTER :: {{ type_def.name }}_INTERN
		
		ALLOCATE({{ type_def.name}}_INTERN)
		{{ type_def.name }}_NEW = C_LOC({{ type_def.name }}_INTERN)
	END FUNCTION
	
	SUBROUTINE {{ type_def.name }}_FREE({{ type_def.name }}_INST) BIND('C', NAME="{{ type_def.name }}_free")
		TYPE(C_PTR), VALUE, INTENT(IN) :: {{ type_def.name }}_INST
		TYPE({{ type_def.name }}), POINTER :: {{ type_def.name }}_INTERN
		
		CALL C_F_POINTER({{ type_def.name }}_INST, {{ type_def.name }}_INTERN)
		DEALLOCATE({{ type_def.name }}_INTERN)
	END SUBROUTINE
	{% for field in type_def.fields %}
	FUNCTION {{ type_def.name }}_GET_{{ field.name }}({{ type_def.name }}_INTERN) BIND('C', NAME="{{ type_def.name }}_get_{{ field.name }}")
		INTEGER :: {{ type_def.name }}_GET_{{ field.name }}
		TYPE(C_PTR), VALUE, INTENT(IN) :: {{ type_def.name }}_INST
		TYPE({{ type_def.name }}), POINTER :: {{ type_def.name }}_INTERN
		
		CALL C_F_POINTER({{ type_def.name }}_INST, {{ type_def.name }}_INTERN)
		{{ type_def.name }}_GET_{{ field.name }} = {{ type_def.name }}_INTERN%{{ field.name }}
	END FUNCTION
	
	SUBROUTINE {{ type_def.name }}_SET_{{ field.name }}({{ type_def.name }}_INTERN, {{ field.name }}_VALUE) BIND('C', NAME="{{ type_def.name }}_set_{{ field.name }}")
		TYPE(C_PTR), VALUE, INTENT(IN) :: {{ type_def.name }}_INST
		INTEGER, VALUE, INTENT(IN) :: {{ field.name }}_VALUE
		TYPE({{ type_def.name }}), POINTER :: {{ type_def.name }}_INTERN

		CALL C_F_POINTER({{ type_def.name }}_INST, {{ type_def.name }}_INTERN)
		{{ type_def.name }}_INTERN%{{ field.name }} = {{ field.name }}_VALUE
	END SUBROUTINE
	{% endfor -%}
{% endfor %}
END
