{#-#################################################################################################################-#}
{#- F2x-Template: _bindc.f90.t                                                                                      -#}
{#-                                                                                                                 -#}
{#- This template generates a wrapper around Fortran routines that are usable from C code. This is done by using    -#}
{#- the BIND(C) standard to generate compatible interface.                                                          -#}
{#-#################################################################################################################-#}
{%- import "_bindc_types.f90.tl" as type_lib -%}

! This file was generated by F2x using '_bindc.f90.t'. Please do not edit manually.
MODULE {{ module.name }}_BINDC
	USE, INTRINSIC :: ISO_C_BINDING
	USE C_INTERFACE_MODULE
{%- for use in module.uses %}
    USE {{ use }}
{%- endfor %}
    USE {{ module.name }}

CONTAINS
{#-=================================================================================================================-#}
{#- Derived types                                                                                                   -#}
{%- for type in module.types %}

    !------------------------------------------------------------------------------------------------------------------
    ! TYPE({{ type.name }}) from {{ module.name }}
    {{ type_lib.constructor(type) }}

    {{ type_lib.destructor(type) }}
    {%- for field in type.fields %}
    {{ type_lib.allocator(type, field) }}
    {{ type_lib.getter(type, field) }}
    {{ type_lib.setter(type, field) }}
    {%- endfor %}
    !------------------------------------------------------------------------------------------------------------------
{%- endfor %}

END
