MODULE WRAP_UTIL
	USE, INTRINSIC :: ISO_C_BINDING

	IMPLICIT NONE

	PRIVATE

	PUBLIC C_F_STRING
	PUBLIC F_C_STRING

CONTAINS

	SUBROUTINE C_F_STRING(C_STRING, C_STRING_LEN, F_STRING)
		TYPE(C_PTR), INTENT(IN) :: C_STRING
		INTEGER, INTENT(IN) :: C_STRING_LEN
		CHARACTER(LEN=C_STRING_LEN), INTENT(OUT) :: F_STRING
		CHARACTER(LEN=1, KIND=C_CHAR), DIMENSION(:), POINTER :: C_STRING_INTERN
		INTEGER :: I

		CALL C_F_POINTER(C_STRING, C_STRING_INTERN, [huge(0)])
		F_STRING(:) = ' '
		DO I = 1, C_STRING_LEN
			IF (C_STRING_INTERN(I) == C_NULL_CHAR) EXIT
			F_STRING(I:I) = C_STRING_INTERN(I)
		END DO
	END SUBROUTINE

	SUBROUTINE F_C_STRING(F_STRING, C_STRING_LEN, C_STRING)
	    CHARACTER(LEN=C_STRING_LEN), INTENT(IN) :: F_STRING
	    INTEGER, INTENT(IN) :: C_STRING_LEN
	    TYPE(C_PTR), INTENT(IN) :: C_STRING
	    CHARACTER(LEN=1, KIND=C_CHAR), DIMENSION(:), POINTER :: C_STRING_INTERN
	    INTEGER :: I, STRLEN

	    STRLEN = MIN(C_STRING_LEN, LEN(F_STRING))
	    CALL C_F_POINTER(C_STRING, C_STRING_INTERN, [STRLEN + 1])
	    DO I = 1, STRLEN
	        C_STRING_INTERN(I) = F_STRING(I:I)
	    END DO
	    C_STRING_INTERN(I + 1) = C_NULL_CHAR
	END SUBROUTINE

END MODULE
