{#- Copyright 2018 German Aerospace Center (DLR)                                                                     -#}
{#-                                                                                                                  -#}
{#- Licensed under the Apache License, Version 2.0 (the "License");                                                  -#}
{#- you may not use this file except in compliance with the License.                                                 -#}
{#- You may obtain a copy of the License at                                                                          -#}
{#-                                                                                                                  -#}
{#-     http://www.apache.org/licenses/LICENSE-2.0                                                                   -#}
{#-                                                                                                                  -#}
{#- Unless required by applicable law or agreed to in writing, software                                              -#}
{#- distributed under the License is distributed on an "AS IS" BASIS,                                                -#}
{#- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.                                         -#}
{#- See the License for the specific language governing permissions and                                              -#}
{#- limitations under the License.                                                                                   -#}


{#- Import macro collections -#}
{%- import "pyx/types.pyx.tl" as types with context -%}
{%- import "pyx/methods.pyx.tl" as methods with context -%}


# -*- coding: {{ config.get('generate', 'encoding') }} -*-
#
# '{{ context.basename }}' generated by F2x 'pyx/_cyglue.pyx.t' template. Do not edit manually.


{%- if module.types -%}
    {{ types.export() }}
{%- endif -%}


{%- if module.methods -%}
    {{ methods.export() }}
{%- endif -%}
