"""
ctypes_err

Generates a Python module that interacts with a ISO C interface generated by 'bindc' template using ctypes including
error handling using 'cerr' template.
"""
templates = ['@ctypes_err/_glue.py.t']
depends = ['cerr']
modules = ['glue.py']
libraries = None
