"""
ctypes

Generates a Python module that interacts with a ISO C interface generated by 'bindc' template using ctypes.
"""
templates = ['@ctypes/_glue.py.t']
depends = ['bindc']
modules = ['glue.py']
libraries = None
