{#-##################################################################################################################-#}
{#- F2x 'bindc' main template.                                                                                       -#}
{#-                                                                                                                  -#}
{#- This template generates a FORTRAN wrapper module that provides `BIND(C)` interfaces to FORTRAN derived types,    -#}
{#- `FUNCTION`s and `SUBROUTINE`s.                                                                                   -#}
{#-                                                                                                                  -#}
{#- Copyright 2018 German Aerospace Center (DLR)                                                                     -#}
{#-                                                                                                                  -#}
{#- Licensed under the Apache License, Version 2.0 (the "License");                                                  -#}
{#- you may not use this file except in compliance with the License.                                                 -#}
{#- You may obtain a copy of the License at                                                                          -#}
{#-                                                                                                                  -#}
{#-     http://www.apache.org/licenses/LICENSE-2.0                                                                   -#}
{#-                                                                                                                  -#}
{#- Unless required by applicable law or agreed to in writing, software                                              -#}
{#- distributed under the License is distributed on an "AS IS" BASIS,                                                -#}
{#- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.                                         -#}
{#- See the License for the specific language governing permissions and                                              -#}
{#- limitations under the License.                                                                                   -#}
{#-##################################################################################################################-#}


{#- Import helper libraries. -#}
{%- import "types.f90.tl" as types with context -%}
{#%- import "globals.f90.tl" as vars with context -%#}
{%- import "methods.f90.tl" as methods with context %}


! This module was generated by the F2x 'bindc' template. Please do not modify it directly.
MODULE {{ module.name }}_GLUE
    USE F2X_BINDC
    USE {{ module.name }}
{%- for module_name in module.uses %}
    USE {{ module_name }}
{%- endfor %}

    IMPLICIT NONE

CONTAINS
{%- for type in module.types  %}
    {%- if type.public %}
    {{ types.export(type) }}
    {% endif %}
{%- endfor %}

{# %- if module.globals %}
    !===================================================================================================================
    ! Globals
    {%- for global in module.globals %}
    {{ vars.export_global(global) }}
    {%- endfor %}
{%- endif % #}

{%- if module.methods %}
    !===================================================================================================================
    ! Exported subroutines and functions
    {%- for method in module.methods %}
    {{ methods.export(method) }}
    {% endfor %}
{%- endif %}
END
