MODULE SUB_CALL

    PUBLIC

CONTAINS

    SUBROUTINE INPUT_ARGS(I, X, IS)
        INTEGER, INTENT(IN) :: I
        REAL, INTENT(IN) :: X
        LOGICAL, INTENT(IN) :: IS

        WRITE (*, *) I, X, IS
    END SUBROUTINE

    FUNCTION RETURN_INTEGER()
        INTEGER :: RETURN_INTEGER

        RETURN_INTEGER = 42
    END FUNCTION

END
